# 主题配置
theme: minima

# 博客基本信息
title: 羡鱼的博客
author: 羡鱼
description: 这是我的个人博客，分享我的想法、项目和生活点滴。

# 社交链接
social_links:
  github: xianyuzinc
  linkedin: 你的用户名

# 其他配置
email: 你的邮箱
url: "https://xianyuzinc.github.io"
baseurl: ""

# Markdown 配置
markdown: kramdown
highlighter: rouge

# 语言设置
lang: zh-CN

# 其他自定义配置
plugins:
  - jekyll-feed
  - jekyll-seo-tag
